const LABELSIZES = [
    {id: 1, type: "circular", sizeName: "Chica 4cm", height: 4, width: 4, titleFontSize: 0.7, subtitleFontSize: 0.45}
    ,{id: 2, type: "circular", sizeName: "Mediana 4.5cm", height: 4.5, width: 4.5, titleFontSize: 0.8, subtitleFontSize: 0.6}
    ,{id: 3, type: "circular", sizeName: "Grande 6cm", height: 6, width: 6, titleFontSize: 1.1, subtitleFontSize: 0.7}
]

const BARCODENAMES = [
    "Acondicionador Solido",
    "Balsamo Labial",
    "Bolsa De Arnica Seca",
    "Bolsa De Espinosilla Seca",
    "Bolsa De Marrubio Seca",
    "Cepillo De Bambu",
    "Crema Arnica, Calendula",
    "Crema Chica numero 8 Manzanilla, Miel",
    "Crema Grande numero 10 Manzanilla, Miel",
    "Crema Tepezcohuite, Cuachalalte",
    "Desodorante Alumbre",
    "Desodorante Leche Magnesia",
    "Desodorante Solido Coco, Karite, Bicarbonato",
    "Exfoliante Bicarbonato y Coco",
    "Gel Antibacterial Manos Arnica 250ml Con Dispensador",
    "Gel Antibacterial Manos Arnica Con Dispensador 1L",
    "Gel Antibacterial Manos Arnica Con Dispensador 300ml",
    "Gel Antibacterial Manos Arnica Sin Dispensador 250ml",
    "Gel Antibacterial Manos Arnica Sin Dispensador 500ml",
    "Gel Arnica",
    "Jabon  Solido Cafe Miel",
    "Jabon De Tepezcohuite Miel",
    "Jabon Liquido Antibacterial 250 Ml Con Arnica",
    "Jabon Liquido Antibacterial Con Arnica 500 Ml Sin Dispensador",
    "Jabon Liquido Antibacterial Con Dispensador 500 Ml",
    "Jabon Solido Arnica Miel",
    "Jabon Solido Arroz Y miel",
    "Jabon Solido Avena Miel",
    "Jabon Solido Carbon",
    "Jabon Solido De Marrubio Azomiate",
    "Jabon Solido De Romero Miel",
    "Jabon Solido De Rosa De Castilla",
    "JABON SOLIDO DE TEPEZCOHIUTE Y CUACAHALALATE",
    "Jabon Solido Espinosilla y Arnica Higiene Intima",
    "Jabon Solido Manzanilla Y Miel",
    "Jabon Solido Miel",
    "Pomada Arnica",
    "Shampoo Liquido Anticaida Romero, Espinosilla 250ml",
    "Shampoo Liquido Anticaida Romero, Espinosilla 500ml",
    "Shampoo Liquido Antipiojos Ruda 250ml",
    "Shampoo Liquido Cascara De Nuez 250ml",
    "Shampoo Liquido Cascara De Nuez 500ml",
    "Shampoo Liquido Manzanilla, Miel 250ml",
    "Shampoo Liquido Manzanilla, Miel 500ml",
    "Shampoo Liquido Romero, Cola De Caballo 250ml",
    "Shampoo Liquido Romero, Cola De Caballo 500ml",
    "Shampoo Solido Carbon Activado, Citricos",
    "Shampoo Solido Flor De Hibisco, Citricos",
    "Shampoo Solido Romero",
];
  